"""CI workflow scaffold (PH-12 Slice 12.1).

Generates ``.github/workflows/ci.yml`` tuned to the detected
stack. Each language template is a deterministic string render
— no third-party templating engine, no YAML library required.
The result is plain text the operator can hand-tune; we never
overwrite without ``--force``.

Cross-platform: pure stdlib.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .stack_detector import DetectedStack, detect_stack


CI_WORKFLOW_PATH = Path(".github") / "workflows" / "ci.yml"


@dataclass
class CIScaffoldResult:
    """Outcome of :func:`scaffold_ci_workflow`. ``written`` is
    True when the file actually landed on disk."""

    target: Path
    body: str
    stack: DetectedStack
    written: bool = False
    skipped_reason: str = ""
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "target": str(self.target),
            "stack": self.stack.to_dict(),
            "written": self.written,
            "skipped_reason": self.skipped_reason,
            "notes": list(self.notes),
            "body_chars": len(self.body),
        }


# ---- Per-language templates ------------------------------------------


def _render_python(stack: DetectedStack) -> str:
    """Render a Python-friendly GitHub Actions workflow."""
    py_min = stack.python_min_version or ">=3.10"
    # Best-effort matrix: pin to the floor stated in pyproject.
    floor = "3.10"
    if py_min.lstrip(">=").strip().startswith(("3.11", "3.12", "3.13")):
        floor = py_min.lstrip(">=").strip().split(",")[0].strip()
    matrix = [floor]
    if floor != "3.12":
        matrix.append("3.12")

    has_pytest = stack.python_test_runner == "pytest"
    has_ruff = "ruff" in stack.python_linters
    has_mypy = "mypy" in stack.python_linters

    steps: list[str] = []
    if has_ruff:
        steps.append('      - name: Lint (ruff)\n        run: python -m ruff check .')
    if has_mypy:
        steps.append('      - name: Type-check (mypy)\n        run: python -m mypy .')
    if has_pytest:
        steps.append('      - name: Test (pytest)\n        run: python -m pytest -q')
    if not steps:
        steps.append('      - name: Sanity (pytest)\n        run: python -m pytest -q || echo "no tests yet"')

    matrix_yaml = "\n".join(f'          - "{v}"' for v in matrix)

    return f"""# Generated by `mythic-vibe ci scaffold` (PH-12 Slice 12.1).
# Stack detected: python (test_runner={stack.python_test_runner or "unknown"},
# linters={list(stack.python_linters)}, min_version={py_min}).
# Hand-tune freely; re-run with --force to regenerate.

name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
{matrix_yaml}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{{{ matrix.python-version }}}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{{{ matrix.python-version }}}}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]' || pip install -e '.[test]' || pip install -e .
{chr(10).join(steps)}
"""


def _render_node(stack: DetectedStack) -> str:
    """Render a Node-friendly GitHub Actions workflow."""
    pm = stack.node_package_manager or "npm"
    install_cmd = {
        "npm": "npm ci || npm install",
        "yarn": "yarn install --frozen-lockfile",
        "pnpm": "pnpm install --frozen-lockfile",
    }.get(pm, "npm install")

    test_cmd = stack.node_test_command or f"{pm} test"
    lint_cmd = stack.node_lint_command

    steps = [
        '      - name: Install dependencies\n        run: ' + install_cmd,
        '      - name: Test\n        run: ' + test_cmd,
    ]
    if lint_cmd:
        steps.insert(1, '      - name: Lint\n        run: ' + lint_cmd)

    return f"""# Generated by `mythic-vibe ci scaffold` (PH-12 Slice 12.1).
# Stack detected: node (package_manager={pm}).

name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20", "22"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node ${{{{ matrix.node-version }}}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{{{ matrix.node-version }}}}
{chr(10).join(steps)}
"""


def _render_rust() -> str:
    return """# Generated by `mythic-vibe ci scaffold` (PH-12 Slice 12.1).
# Stack detected: rust.

name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Lint (clippy)
        run: cargo clippy -- -D warnings
      - name: Format check
        run: cargo fmt -- --check
      - name: Test
        run: cargo test
"""


def _render_go() -> str:
    return """# Generated by `mythic-vibe ci scaffold` (PH-12 Slice 12.1).
# Stack detected: go.

name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
"""


def _render_unknown(stack: DetectedStack) -> str:
    return f"""# Generated by `mythic-vibe ci scaffold` (PH-12 Slice 12.1).
# Stack detection inconclusive (no recognised manifest).
# Detected languages: {list(stack.detected_languages) or 'none'}.
#
# Hand-tune the steps below for your project's tooling.

name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TODO — install your dependencies here
        run: echo "no install configured"
      - name: TODO — run your tests here
        run: echo "no tests configured"
"""


def render_ci_workflow(stack: DetectedStack) -> str:
    """Pick the right per-language template for ``stack``. Falls
    back to a TODO scaffold when nothing is recognised."""
    primary = stack.primary_language
    if primary == "python":
        return _render_python(stack)
    if primary == "node":
        return _render_node(stack)
    if primary == "rust":
        return _render_rust()
    if primary == "go":
        return _render_go()
    return _render_unknown(stack)


# ---- Orchestration ---------------------------------------------------


def scaffold_ci_workflow(
    root: Path,
    *,
    force: bool = False,
    dry_run: bool = False,
) -> CIScaffoldResult:
    """Detect the stack and (unless ``dry_run``) write the
    workflow YAML. ``force`` overwrites an existing file;
    otherwise the existing file is left in place and the result
    captures the conflict in ``skipped_reason``."""
    stack = detect_stack(root)
    body = render_ci_workflow(stack)
    target = Path(root) / CI_WORKFLOW_PATH

    result = CIScaffoldResult(target=target, body=body, stack=stack)

    if dry_run:
        result.notes.append("dry-run; no file written")
        return result

    if target.is_file() and not force:
        result.skipped_reason = (
            f"{target} already exists. Re-run with --force to overwrite."
        )
        return result

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")
    result.written = True
    return result


__all__ = [
    "CI_WORKFLOW_PATH",
    "CIScaffoldResult",
    "render_ci_workflow",
    "scaffold_ci_workflow",
]
