"""Dockerfile + .dockerignore + docker-compose scaffold (PH-12 Slice 12.2).

Generates a minimal multi-stage Dockerfile, a permissive
``.dockerignore``, and a single-service ``docker-compose.yml``
tuned to the detected stack (slice 12.1's ``DetectedStack``).

Same conventions as the CI scaffold: deterministic string
templates, ``--force`` to overwrite, ``--dry-run`` to preview.

Cross-platform: pure stdlib.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .stack_detector import DetectedStack, detect_stack


DOCKERFILE_PATH = Path("Dockerfile")
DOCKERIGNORE_PATH = Path(".dockerignore")
DOCKER_COMPOSE_PATH = Path("docker-compose.yml")


@dataclass
class DockerScaffoldFile:
    """One file the scaffold would write."""

    target: Path
    body: str
    written: bool = False
    skipped_reason: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "target": str(self.target),
            "body_chars": len(self.body),
            "written": self.written,
            "skipped_reason": self.skipped_reason,
        }


@dataclass
class DockerScaffoldResult:
    stack: DetectedStack
    files: list[DockerScaffoldFile] = field(default_factory=list)

    @property
    def written_count(self) -> int:
        return sum(1 for f in self.files if f.written)

    def to_dict(self) -> dict[str, Any]:
        return {
            "stack": self.stack.to_dict(),
            "files": [f.to_dict() for f in self.files],
            "written_count": self.written_count,
        }


# ---- Dockerfile templates --------------------------------------------


_DOCKERFILE_PYTHON = """# Generated by `mythic-vibe docker scaffold` (PH-12 Slice 12.2).
# Stack: python.

FROM python:3.12-slim AS builder
WORKDIR /app
COPY pyproject.toml ./
COPY . .
RUN pip install --upgrade pip && pip install --no-cache-dir -e . || pip install --no-cache-dir .

FROM python:3.12-slim AS runtime
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY . .
# TODO: replace with your project's actual entrypoint.
CMD ["python", "-m", "your_package"]
"""


_DOCKERFILE_NODE = """# Generated by `mythic-vibe docker scaffold` (PH-12 Slice 12.2).
# Stack: node.

FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci || npm install
COPY . .
RUN npm run build || echo "no build step"

FROM node:20-alpine AS runtime
WORKDIR /app
COPY --from=builder /app /app
ENV NODE_ENV=production
# TODO: replace with your project's actual start script.
CMD ["npm", "start"]
"""


_DOCKERFILE_RUST = """# Generated by `mythic-vibe docker scaffold` (PH-12 Slice 12.2).
# Stack: rust.

FROM rust:1.79-slim AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim AS runtime
WORKDIR /app
# TODO: replace with the actual binary name from Cargo.toml.
COPY --from=builder /app/target/release/* /usr/local/bin/
CMD ["app"]
"""


_DOCKERFILE_GO = """# Generated by `mythic-vibe docker scaffold` (PH-12 Slice 12.2).
# Stack: go.

FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN go build -o /app/main ./...

FROM gcr.io/distroless/base-debian12 AS runtime
COPY --from=builder /app/main /app/main
USER nonroot:nonroot
CMD ["/app/main"]
"""


_DOCKERFILE_UNKNOWN = """# Generated by `mythic-vibe docker scaffold` (PH-12 Slice 12.2).
# Stack: detection inconclusive.

FROM debian:bookworm-slim
WORKDIR /app
COPY . .
# TODO: install your dependencies.
# TODO: replace with your project's actual entrypoint.
CMD ["echo", "Configure mythic-vibe docker scaffold for your stack"]
"""


def _render_dockerfile(stack: DetectedStack) -> str:
    primary = stack.primary_language
    if primary == "python":
        return _DOCKERFILE_PYTHON
    if primary == "node":
        return _DOCKERFILE_NODE
    if primary == "rust":
        return _DOCKERFILE_RUST
    if primary == "go":
        return _DOCKERFILE_GO
    return _DOCKERFILE_UNKNOWN


# ---- .dockerignore + docker-compose templates ------------------------


_DOCKERIGNORE_BODY = """# Generated by `mythic-vibe docker scaffold` (PH-12 Slice 12.2).

.git
.github
.mypy_cache
.ruff_cache
.pytest_cache
__pycache__
*.pyc
node_modules
target
dist
build
*.egg-info
.venv
venv
.env
.env.*
*.pem
*.key
*.token
mythic/
"""


def _render_docker_compose(stack: DetectedStack) -> str:
    primary = stack.primary_language
    service_name = "app"
    if primary == "node":
        service_name = "node-app"
    elif primary == "python":
        service_name = "python-app"
    elif primary == "rust":
        service_name = "rust-app"
    elif primary == "go":
        service_name = "go-app"

    return f"""# Generated by `mythic-vibe docker scaffold` (PH-12 Slice 12.2).
# Stack: {primary}.

services:
  {service_name}:
    build: .
    image: {service_name}:latest
    # TODO: configure ports / volumes / environment.
    # ports:
    #   - "8080:8080"
    # environment:
    #   - LOG_LEVEL=info
    restart: unless-stopped
"""


# ---- Orchestration ---------------------------------------------------


def scaffold_docker(
    root: Path,
    *,
    force: bool = False,
    dry_run: bool = False,
) -> DockerScaffoldResult:
    """Detect the stack and (unless ``dry_run``) write Dockerfile,
    .dockerignore, and docker-compose.yml. ``force`` overwrites
    existing files; otherwise existing files are left in place
    and the per-file ``skipped_reason`` reports the conflict."""
    stack = detect_stack(root)
    result = DockerScaffoldResult(stack=stack)

    plan: tuple[tuple[Path, str], ...] = (
        (DOCKERFILE_PATH, _render_dockerfile(stack)),
        (DOCKERIGNORE_PATH, _DOCKERIGNORE_BODY),
        (DOCKER_COMPOSE_PATH, _render_docker_compose(stack)),
    )

    for relative, body in plan:
        target = Path(root) / relative
        entry = DockerScaffoldFile(target=target, body=body)
        if dry_run:
            result.files.append(entry)
            continue
        if target.is_file() and not force:
            entry.skipped_reason = (
                f"{target} already exists. Re-run with --force to overwrite."
            )
            result.files.append(entry)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
        entry.written = True
        result.files.append(entry)

    return result


__all__ = [
    "DOCKERFILE_PATH",
    "DOCKERIGNORE_PATH",
    "DOCKER_COMPOSE_PATH",
    "DockerScaffoldFile",
    "DockerScaffoldResult",
    "scaffold_docker",
]
