"""Fetch python-build-standalone SHA256 checksums for the
launcher's pinned release tag (PH-23.4).

The launcher (`packaging/launcher/src/main.rs`) ships a
`PBS_EXPECTED_SHA256` table that the verification path checks
downloaded archives against. This script fetches the upstream
SHA256 manifest and prints the table populated with the real
values — paste the output into `main.rs`.

Usage:
    python tools/fetch_pbs_checksums.py
    python tools/fetch_pbs_checksums.py --tag 20241016 --version 3.12.7

The script requires only the stdlib (urllib + hashlib). It does
not need to download the full archives — python-build-standalone
publishes a SHA256SUMS file per release that we parse directly.

If the upstream layout changes, update SHA256SUMS_URL_PATTERN.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from mythic_vibe_cli.runtime.script_guard import guarded_main


# Default values — must match the PYTHON_VERSION + PBS_RELEASE_TAG
# constants in packaging/launcher/src/main.rs. Bumping either
# here without bumping there (or vice versa) produces a stale
# table; the launcher's verification path catches that drift at
# runtime, but the script's defaults stay synced with the Rust
# source by convention.
DEFAULT_PYTHON_VERSION = "3.12.7"
DEFAULT_PBS_RELEASE_TAG = "20241016"

# Each python-build-standalone release publishes a SHA256SUMS
# file at this URL pattern listing one line per release asset
# in the form `<sha256>  <filename>`.
SHA256SUMS_URL_PATTERN = (
    "https://github.com/indygreg/python-build-standalone/releases/"
    "download/{tag}/SHA256SUMS"
)

# Triples we care about — must match host_target_triple()'s match
# arms in main.rs.
SUPPORTED_TRIPLES = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]

# Asset name pattern — install_only.tar.gz is the smallest
# variant that includes a complete CPython suitable for venv
# creation. The launcher pulls install_only.tar.gz exclusively;
# this script filters the SHA256SUMS file to those rows.
ASSET_FILENAME_PATTERN = (
    "cpython-{version}+{tag}-{triple}-install_only.tar.gz"
)


def fetch_sha256sums(tag: str) -> str:
    """Download the SHA256SUMS manifest for the given release.
    Returns the raw text body.
    """
    url = SHA256SUMS_URL_PATTERN.format(tag=tag)
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            return resp.read().decode("utf-8")
    except urllib.error.URLError as exc:
        raise RuntimeError(f"failed to fetch {url}: {exc}") from exc


def parse_sums(body: str) -> dict[str, str]:
    """Parse a `<sha>  <filename>` SHA256SUMS body into a dict
    mapping filename -> sha256."""
    out: dict[str, str] = {}
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([0-9a-fA-F]{64})\s+\*?(.+)$", line)
        if m:
            out[m.group(2)] = m.group(1).lower()
    return out


def render_table(version: str, tag: str, sums: dict[str, str]) -> str:
    """Render the populated PBS_EXPECTED_SHA256 table as Rust
    source ready to paste into main.rs."""
    lines: list[str] = [
        f"// Generated by tools/fetch_pbs_checksums.py for "
        f"PBS release {tag} + Python {version}.",
        "// Each entry is (host_target_triple, sha256_lowercase_hex).",
        "pub const PBS_EXPECTED_SHA256: &[(&str, Option<&str>)] = &[",
    ]
    for triple in SUPPORTED_TRIPLES:
        asset = ASSET_FILENAME_PATTERN.format(
            version=version, tag=tag, triple=triple,
        )
        sha = sums.get(asset)
        if sha is None:
            lines.append(
                f'    ("{triple}", None),  // MISSING — '
                f'asset {asset} not in upstream SHA256SUMS',
            )
        else:
            lines.append(f'    ("{triple}", Some("{sha}")),')
    lines.append("];")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Fetch and render the python-build-standalone "
            "SHA256 table for the launcher (PH-23.4)."
        ),
    )
    parser.add_argument(
        "--tag",
        default=DEFAULT_PBS_RELEASE_TAG,
        help="python-build-standalone release tag "
             f"(default: {DEFAULT_PBS_RELEASE_TAG})",
    )
    parser.add_argument(
        "--version",
        default=DEFAULT_PYTHON_VERSION,
        help=f"CPython version (default: {DEFAULT_PYTHON_VERSION})",
    )
    args = parser.parse_args(argv)

    try:
        body = fetch_sha256sums(args.tag)
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    sums = parse_sums(body)

    if not sums:
        print(
            "ERROR: SHA256SUMS body parsed empty — "
            "upstream layout may have changed",
            file=sys.stderr,
        )
        return 2

    table = render_table(args.version, args.tag, sums)
    print(table)
    print()
    print(
        "# Paste the const above into "
        "packaging/launcher/src/main.rs, replacing the existing "
        "PBS_EXPECTED_SHA256 declaration.",
    )
    return 0


if __name__ == "__main__":
    sys.exit(
        guarded_main(
            lambda: main(),
            script_name=Path(__file__).name,
            json_mode=False,
        )
    )
